version: '3'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    command: ["./scripts/wait-for-pg.sh", "postgres", "npm", "run", "start:prod"]
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - modules:/usr/src/app/node_modules
      - ./:/usr/src/app
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
volumes:
  modules:
  pg_data:
