version: '3'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - modules:/usr/src/app/node_modules
      - ./:/usr/src/app
  postgres:
    image: postgres:11-alpine
    depends_on:
      - backend
    environment:
      - POSTGRES_PASSWORD=123
  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
volumes:
  modules:
